### ISSUE TITLE
Job Postings. 

### ISSUE THREAD

**Issue by Firdaws-b** [COENS-SOENS/-COENS-SOENS-soen341project2023-#46]
As a user, i want to have access to different job postings available on the website, so that i can edit, modify and add  a job.

**Comment by Firdaws-b** [comment]
#43

**Comment by BayanAlsalem** [comment]
### AT - 1.1: Create a Job Listing 

**User Acceptance Flow:**

1. User Signs in.
2. User clicks “Create a job” button on the navigation bar in the employer’s dashboard.
3. User fills in the job title.
4. User fills in the job description.
5. User fills in the salary field.
6. User clicks “share” button under the job card. 
                 a. If user forgets any field, then error message shows up.
7. Data is saved in the database and User is directed to the dashboard.
