### ISSUE TITLE
AT-1: Create a Job Listing

### ISSUE THREAD

**Issue by BayanAlsalem** [COENS-SOENS/-COENS-SOENS-soen341project2023-#53]
This acceptance test is for  #47 

User Acceptance Flow:

1. User Signs in.
2. User clicks “Create a job” button on the navigation bar in the employer’s dashboard.
3. User fills in the job title.
4. User fills in the job description.
5. User fills in the salary field.
6. User clicks “share” button under the job card.
         a. If employer forgets any field, then error message shows up.
7. Data is saved in the database and User is directed to the dashboard.

**Comment by Firdaws-b** [comment]
#43
