### ISSUE TITLE
AT-2: Create an employer account

### ISSUE THREAD

**Issue by BayanAlsalem** [COENS-SOENS/-COENS-SOENS-soen341project2023-#54]
**This acceptance test is for** #16  

User Acceptance Flow:

1. User clicks “Sign up” button on the navigation bar in the homepage.
2. User clicks “Employer” button in the type of user page.
3. User fills in his/her first and last name.
4. User in his/her email address and password.
5. User clicks “Sign up” button to register.
6. User directs to the employer dashboard.

**Comment by Firdaws-b** [comment]
#16
