### ISSUE TITLE
AT-3: Sign in as a user

### ISSUE THREAD

**Issue by BayanAlsalem** [COENS-SOENS/-COENS-SOENS-soen341project2023-#55]
**This acceptance test is for** #17 

User Acceptance Flow:

1. User clicks "Sign in" button on the navigation bar in the homepage.
2. User fills in the email address and the password.
  a. If user enters an ill-formatted email, then error message shows up.
  b. If user forgets any field, then error message shows up.
3. User clicks "Sign in" button at the bottom of the login card/widget.
4. User directs to the dashboard.

**Comment by Firdaws-b** [comment]
#17
